spin_version = "1"
name = "finicky-whiskers-session"
version = "0.1.0"
trigger = { type = "http", base = "/" }

[[component]]
id = "ruby"
source = "session.wasm"
[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/session.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/session"
